import os, re
from groq import Groq
from youtube_transcript_api import YouTubeTranscriptApi

VID = "jAv3EU1YEo4"
client = Groq()

# 1. Headless transcript ingestion (no scrapers, no manual download)
lines = [(e.start, e.text) for e in YouTubeTranscriptApi().fetch(VID, languages=["hi", "en"])]
def fmt(t):
    t = int(t); return f"{t//60:02d}:{t%60:02d}"

transcript = "\n".join([f"[{fmt(s)}] {x}" for s, x in lines])

# 2. LLM packaging (handles Hinglish — BART would fail on Hindi)
prompt = f"""You are a YouTube content strategist for a Mumbai lifestyle vlogger. From this transcript produce:
1. CHAPTERS: 5 timestamped chapters using the [mm:ss] markers, titles max 8 words.
2. DESCRIPTION: one energetic 80-word YouTube description.
3. HOOKS: 3 one-line Shorts/Reels hooks, curiosity-driven.
4. HASHTAGS: 5 hashtags.
Transcript:
{transcript[:12000]}"""

out = client.chat.completions.create(
    model="qwen/qwen3.8-27b",
    messages=[{"role": "user", "content": prompt}],
    temperature=0.7
).choices[0].message.content

md = f"# Auto Content Package — MSK vlog (demo)\n\n{out}\n\n---\nGenerated by a headless pipeline: transcript ingestion → LLM packaging. Built in 30 minutes as a proof of concept by Parth Keskar."
open("MSK_DEMO.md", "w").write(md)
print(md)